apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: haproxy
  labels:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.8.2
    helm.sh/chart: haproxy-1.19.3
  annotations:
    meta.helm.sh/release-name: haproxy
    meta.helm.sh/release-namespace: haproxy
data:
  haproxy.cfg: |

    global
      log stdout format raw local0
      maxconn 1024

    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s

    frontend fe_main
      bind :80
      default_backend be_main

    backend be_main
      server cluster2 43.129.230.85:80 check
      server cluster3 101.32.37.249:80 check
