apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: haproxy
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "cert-manager-webhook-dnspod-cluster-issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: bookinfo.starmooc.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: haproxy
                port:
                  number: 80
  tls:
  - hosts:
    - bookinfo.starmooc.net
    secretName: bookinfo-crt-secret 