unclassified:
  githubpluginconfig:
    configs:
      - name: "GitHub111"
        apiUrl: "https://api.github.com"
        credentialsId: "github-personal-token"
        manageHooks: true
jobs:
  - script: >
      multibranchPipelineJob('image-jenkins') {
        branchSources {
          github {
            // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
            id('test111') // IMPORTANT: use a constant and unique identifier
            scanCredentialsId('github-personal-token')
            repoOwner('orange0217')
            repository('homework')
          }
        }
      }