apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: jenkins
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "cert-manager-webhook-dnspod-cluster-issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: jenkin.starmooc.net
    http:
      paths: 
      - backend:
          service:
            name: jenkins
            port:
              number: 8080
        pathType: ImplementationSpecific
        path: /
  tls:
  - hosts:
    - jenkin.starmooc.net
    secretName: jenkins-crt-secret 


