apiVersion: v1
data:
  haproxy.cfg: |2

    global
      log stdout format raw local0
      maxconn 1024

    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s

    frontend fe_main
      bind :80
      default_backend be_main

    backend be_main
      server cluster2 10.0.0.1:80 check
      server cluster3 :80 check
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: haproxy
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: 2.8.2
    helm.sh/chart: haproxy-1.19.3
  name: ingress-nginx-haproxy
  namespace: haproxy

